stages:
  - install
  - lint
  - test

variables:
  # Paths
  BACKEND_DIR: "$CI_PROJECT_DIR/backend"

backend-install:
  image: node:lts-alpine
  stage: install
  script:
    - cd ${BACKEND_DIR}
    - npm i
  cache:
    key: ${CI_COMMIT_REF_SLUG}-backend
    paths:
      - ${BACKEND_DIR}/node_modules

.backend-lint-base:
  image: node:lts-alpine
  stage: lint
  script:
    - echo ${BACKEND_DIR}
    - ls ${BACKEND_DIR}
    - cd ${BACKEND_DIR}
    - npm run lint
  allow_failure: true
  cache:
    key: ${CI_COMMIT_REF_SLUG}-backend
    paths:
      - ${BACKEND_DIR}/node_modules
    policy: pull

backend-lint-debug:
  extends: .backend-lint-base
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG == null

backend-lint-prod:
  extends: .backend-lint-base
  allow_failure: false
  rules:
    - if: $CI_COMMIT_TAG != null
